services:

  mysql:
    image: mysql:8.4
    container_name: stackoverflow-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: stackoverflow_db
    volumes:
      - stackoverflow_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: stackoverflow-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stackoverflow_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      NOTIFICATION_SERVICE_URL: http://notification-service:8081

  notification-service:
    build: ./notification-service
    container_name: stackoverflow-notifications
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      NOTIFICATION_SMS_MODE: console
      NOTIFICATION_EMAIL_MODE: console

volumes:
  stackoverflow_mysql_data: