name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  notification-service-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: notification-service

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - run: mvn clean test --no-transfer-progress


  java-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - run: mvn clean test --no-transfer-progress


  frontend-tests:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
      - run: npm run test:ci


  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
      - run: npm run lint


  cypress-e2e:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build backend
        working-directory: backend
        run: mvn clean package -DskipTests --no-transfer-progress

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend
        working-directory: frontend
        run: npm ci

      - name: Run E2E tests
        working-directory: frontend
        run: npm run e2e